# Use the official Golang image from the Docker Hub
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Install necessary tools
RUN go install github.com/golang/mock/mockgen@v1.6.0
RUN go install github.com/stretchr/testify

# Run tests
CMD ["go", "test", "./app/controllers/..."]
